extends: airbnb-base

rules:
  no-unused-vars: 0
  no-plusplus: 0
  no-param-reassign: 0
  class-methods-use-this: 0
  no-shadow: 0
  no-extend-native: 0
  no-restricted-syntax: 0
  quotes: 0
  guard-for-in: 0